package constants

const (
	RequestId     = "request-id"
	UserId        = "user-id"
	UserUuid      = "user-uuid"
	UserEmail     = "user-email"
	ApiKey        = "api-key"
	ApiSecret     = "api-secret"
	Signature     = "signature"
	Authorization = "authorization"

	Timestamp = "timestamp"
	Datetime  = "datetime"
	TraceId   = "trace-id"
	SpanId    = "span-id"
	Operation = "operation"
	Component = "component"
	Env       = "env"
	AppName   = "app-name"
	Method    = "method"
	StartTime = "start-time"
	EndTime   = "end-time"
	Duration  = "duration"
	Request   = "request"
	Status    = "status"
	Failed    = "failed"
	Success   = "success"

	Service     = "service"
	Version     = "version"
	Port        = "port"
	Key         = "key"
	Value       = "value"
	Topic       = "topic"
	GroupId     = "group-id"
	Header      = "header"
	Partition   = "partition"
	Offset      = "offset"
	Event       = "event"
	Code        = "code"
	IpAddress   = "ip-address"
	UserAgent   = "user-agent"
	DbHost      = "db-host"
	Timeout     = "timeout"
	ClientId    = "client-id"
	Limit       = "limit"
	CurrentRate = "current-rate"
)
