syntax = "proto3";

package marketdata.v1;

import "google/api/annotations.proto";

option go_package = "/gen/marketdata/v1";

service MarketDataService {
  // @grpc-gateway: GET /api/v1/market/time
  rpc GetServerTime(GetServerTimeRequest) returns (GetServerTimeResponse) {
    option (google.api.http) = {
      get: "/api/v1/market/time"
    };
  };

  // @grpc-gateway: GET /api/v1/market/klines
  rpc GetKlines (GetKlinesRequest) returns (GetKlinesResponse) {
    option (google.api.http) = {
      get: "/api/v1/market/klines" // /api/v1/market/klines?symbol=BTCUSDT&interval=15m&limit=10
    };
  };
  
  // @grpc-gateway: GET /api/v1/market/ticker
  rpc GetTicker (GetTickerRequest) returns (GetTickerResponse) {
    option (google.api.http) = {
      get: "/api/v1/market/ticker/{symbol}" // /api/v1/market/ticker/BTCUSDT
    };
  };
}

// MESSAGES CHO GETSERVERTIME
message GetServerTimeRequest {}
message GetServerTimeResponse {
  int64 server_time = 1;
}

// MESSAGES CHO GETKLINES
message GetKlinesRequest {
  string symbol = 1;   // e.g., "BTCUSDT"
  string interval = 2; // e.g., "1m", "1h", "1d"
  int32 limit = 3;     // max 1000
}
message GetKlinesResponse {
  repeated Kline klines = 1;
}
message Kline {
  int64 open_time = 1;
  string open = 2;
  string high = 3;
  string low = 4;
  string close = 5;
  string volume = 6;
  int64 close_time = 7;
  // ... thêm các trường khác nếu cần
}

// MESSAGES CHO GETTICKER
message GetTickerRequest {
  string symbol = 1; // e.g., "BTCUSDT"
}
message GetTickerResponse {
  string symbol = 1;
  string last_price = 2;
  string price_change_percent = 3;
  string high_24h = 4;
  string low_24h = 5;
  string volume_24h = 6;
}