// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package app

import (
	"github.com/jmoiron/sqlx"
	"go.uber.org/zap"
	"simple-securities/common/client/grpc"
	"simple-securities/internal/user/application/service"
	grpc2 "simple-securities/internal/user/handler/grpc"
	"simple-securities/internal/user/infras/messaging"
	"simple-securities/internal/user/infras/repo"
	"simple-securities/pkg/db/txmanager"
	"simple-securities/pkg/kafka"
)

// Injectors from wire.go:

func InitializeUserHandler(db *sqlx.DB, log *zap.Logger, kafkaManager *kafka.Manager, notiClient *grpc.NotificationGrpcClient, marketClient *grpc.MarketGrpcClient, cryptoClient *grpc.CryptoGrpcClient) (grpc2.UserGrpcSvc, error) {
	txManager := txmanager.NewTxManager(db)
	iUserRepo := repo.NewUserRepo(db)
	iUserHistoryRepo := repo.NewUserHistoryRepo(db)
	iEventPublisher := messaging.NewKafkaEventPublisher(kafkaManager, log)
	registerSvc := service.NewRegisterSvc(txManager, iUserRepo, iUserHistoryRepo, iEventPublisher)
	loginSvc := service.NewLoginSvc(iUserRepo, notiClient, marketClient, cryptoClient, iEventPublisher)
	refreshTokenSvc := service.NewRefreshTokenSvc(iUserRepo)
	getUserProfileSvc := service.NewGetUserProfileSvc(notiClient, iUserRepo, iEventPublisher)
	userGrpcSvc := grpc2.UserGrpcSvc{
		RegisterSvc:       registerSvc,
		LoginSvc:          loginSvc,
		RefreshTokenSvc:   refreshTokenSvc,
		GetUserProfileSvc: getUserProfileSvc,
	}
	return userGrpcSvc, nil
}
