env: dev
app:
  name: crypto-service
  debug: true
  version: v1.0.0
grpc_server:
  port: 50053
  max_connection_idle: 100
  max_connection_age: 7200
  max_connection_age_grace: 60
  time: 10
  timeout: 3
  min_time: 10
  permit_without_stream: true
http_server:
  addr: :8083
  pprof: false
  default_page_size: 10
  max_page_size: 100
  read_timeout: 60s
  write_timeout: 60s
metrics_server:
  addr: :9090
  enabled: true
  path: /metrics
log:
  save_path: ../../log
  file_name: app
  max_size: 100
  max_age: 30
  local_time: true
  compress: true
  level: debug
  enable_console: true
  enable_color: true
  enable_caller: true
  enable_stacktrace: false
mysql:
  user: root
  password: root
  host: 127.0.0.1
  port: 3306
  database: go_hexagonal
  max_idle_conns: 10
  max_open_conns: 100
  max_life_time: 300s
  max_idle_time: 300s
  char_set: utf8mb4
  parse_time: true
  time_zone: Local
redis:
  host: 127.0.0.1
  port: 6379
  password: ""
  db: 0
  poolSize: 10
  idleTimeout: 300
  minIdleConns: 5
postgres:
  user: postgres
  password: postgres
  host: 127.0.0.1
  port: 5432
  database: go_hexagonal
  ssl_mode: disable
  options: ""
  max_connections: 100
  min_connections: 10
  max_conn_lifetime: 300
  idle_timeout: 300
  connect_timeout: 10
  time_zone: UTC
mongodb:
  host: 127.0.0.1
  port: 27017
  database: go_hexagonal
  user: ""
  password: ""
  auth_source: admin
  options: ""
  min_pool_size: 5
  max_pool_size: 100
  idle_timeout: 300
migration_dir: ./migrations