syntax = "proto3";

package spot.v1;

import "google/api/annotations.proto";
// import "common/v1/types.proto";

option go_package = "/gen/spot/v1";

enum OrderSide {
  ORDER_SIDE_UNSPECIFIED = 0;
  ORDER_SIDE_BUY = 1;
  ORDER_SIDE_SELL = 2;
}

enum OrderType {
  ORDER_TYPE_UNSPECIFIED = 0;
  ORDER_TYPE_LIMIT = 1;
  ORDER_TYPE_MARKET = 2;
}

service SpotTradingService {
  // @grpc-gateway: POST /api/v1/spot/order
  rpc PlaceOrder(PlaceOrderRequest) returns (PlaceOrderResponse) {
    option (google.api.http) = {
      post: "/api/v1/spot/order"
      body: "*"
    };
  };

  // @grpc-gateway: GET /api/v1/spot/order/open
  rpc GetOpenOrders(GetOpenOrdersRequest) returns (GetOpenOrdersResponse) {
    option (google.api.http) = {
      get: "/api/v1/spot/order/open" // /api/v1/spot/order/open?symbol=BTCUSDT
    };
  };
}

// MESSAGES CHO PLACEORDER
message PlaceOrderRequest {
  string user_id = 1; // Thường trích xuất từ Auth Token
  string symbol = 2;  // e.g., "BTCUSDT"
  OrderSide side = 3;
  OrderType type = 4;
  string quantity = 5;
  optional string price = 6; // Bắt buộc nếu là LIMIT order
}
message PlaceOrderResponse {
  string order_id = 1;
  string client_order_id = 2;
  string symbol = 3;
  int64 transact_time = 4;
  string status = 5; // NEW, FILLED, v.v.
}

// MESSAGES CHO GETOPENORDERS
message GetOpenOrdersRequest {
  optional string symbol = 1;
}
message GetOpenOrdersResponse {
  repeated Order orders = 1;
}

// Chi tiết lệnh
message Order {
  string order_id = 1;
  string symbol = 2;
  OrderSide side = 3;
  OrderType type = 4;
  string price = 5;
  string quantity = 6;
  string executed_quantity = 7;
  string status = 8;
  int64 time = 9;
}