syntax = "proto3";

package core.v1;

import "google/api/annotations.proto";
import "common/v1/types.proto"; // Import định nghĩa chung

option go_package = "/gen/core/v1";

service UserService {
  // @grpc-gateway: POST /api/v1/auth/register
  rpc Register(RegisterRequest) returns (RegisterResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/register"
      body: "*"
    };
  };

  // @grpc-gateway: POST /api/v1/auth/login
  rpc Login(LoginRequest) returns (LoginResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/login"
      body: "*"
    };
  };

  // @grpc-gateway: POST /api/v1/auth/refresh-token
  rpc RefreshToken(RefreshTokenRequest) returns (RefreshTokenResponse) {
    option (google.api.http) = {
      post: "/api/v1/auth/refresh-token"
      body: "*"
    };
  };

  // @grpc-gateway: GET /api/v1/user/profile
  // Cần Authentication Middleware để xác thực user_id từ token.
  rpc GetUserProfile(GetUserProfileRequest) returns (GetUserProfileResponse) {
    option (google.api.http) = {
      get: "/api/v1/user/profile"
    };
  };
}

// MESSAGES CHO REGISTER
message RegisterRequest {
  string email = 1;
  string password = 2;
}
message RegisterResponse {
  common.v1.UserDto user = 1;
  string access_token = 2;
  string refresh_token = 3;
  string token_type = 4;
  int64 exp = 5;
}

// MESSAGES CHO LOGIN
message LoginRequest {
  string email = 1;
  string password = 2;
}
message LoginResponse {
  common.v1.UserDto user = 1;
  string access_token = 2;
  string refresh_token = 3;
  string token_type = 4;
  int64 exp = 5;
}

// MESSAGES CHO REFRESHTOKEN
message RefreshTokenRequest {
  string refresh_token = 1;
}
message RefreshTokenResponse {
  common.v1.UserDto user = 1;
  string access_token = 2;
  string refresh_token = 3;
  string token_type = 4;
  int64 exp = 5;
}

// MESSAGES CHO GETUSERPROFILE
message GetUserProfileRequest {
  // user_id thường được trích xuất từ Authentication Token
}
message GetUserProfileResponse {
  common.v1.UserDto user = 1;
}